#!/bin/bash

# TODO:
# - Move to /usr/bin/zsh ?

# yadm setup
cd "$HOME"
# echo "Initializing yadm submodules.."
# yadm submodule update --recursive --init

# delete obsolete GitHub readme
rm README.md

# yadm decryption
echo "Attempting to decrypt confidential yadm files.."
yadm decrypt
chmod 400 .ssh/config
chmod 400 .ssh/*.priv
chmod 400 .ssh/*.pub

# zsh setup
echo "Installing zsh and oh-my-zsh.."
pamac install zsh
bash -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
chsh -s $(which zsh) aako

# install / update essentials
echo "Installing packages.."
pamac install telegram-desktop firefox keepass xdotool xsel albert muparser flameshot syncthing syncthing-gtk thunderbird

# programming
pamac install visual-studio-code-bin
pamac install dotnet-runtime dotnet-sdk
#pamac install elixir
# TODO: download and install jetbrains-toolbox from https://www.jetbrains.com/toolbox-app/ or build from AUR ??

# tools and misc.
pamac install gparted teamspeak3 veracrypt veracrypt zenmap ipcalc
pamac install libvirt virt-manager

# psd
# overlayfs SHOULD be loaded automatically as a kernel module as soon as psd attempts the mount
echo "Attempting to install, enable and start profile-sync-daemon.."
pamac install profile-sync-daemon
systemctl --user enable psd
systemctl --user start psd